sudo: required
dist: trusty
install:
 - source ./texlive_install.sh
cache:
  directories:
    - /tmp/texlive
    - $HOME/.texlive
script:
- cd Dokumentation/BlindControl_Doku
# Prefix command with travis_wait x so it times out after 3 mins
- travis_wait 3 pdflatex BlindControl_Doku.tex
- travis_wait 3 bibtex BlindControl_Doku
- travis_wait 3 pdflatex BlindControl_Doku.tex
- cat BlindControl_Doku.log
