sudo: required
dist: trusty
before_install:
- sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-fonts-recommended
  texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-lang-german latex-xcolor
  texlive-pictures
script:
- cd Dokumentation/BlindControl_Doku
- pdflatex -interaction=nonstopmode -halt-on-error BlindControl_Doku.tex
deploy:
  provider: releases
  api_key:
    secure:
    - "$GITHUB_API_KEY"
  file:
  - BlindControl_Doku.pdf
  skip_cleanup: true
  on: 
tags: true
