---
user: l3d
admins:
  - l3d

i3_packages_extra:
  - ranger

i3_keybindings_extra:
  - keybinding:
    name: Volume (mute/unmute)
    key: $mod+F12
    exec: --no-startup-id amixer sset Master toggle
  - keybinding:
    name: Volue (default)
    key: $mod+Shift+F12
    exec: --no-startup-id amixer sset Master 40%

i3_applications:
  - application:
    class: "Firefox"
    name: "firefox"
    workspace: 2
    on_startup: true
  - application:
    class: "Thunderbird"
    name: "thunderbird"
    workspace: 9
    on_startup: true

i3:
  font_size: 12
  focus_follows_mouse: true

i3_desktop_env:
  background: "/home/{{ user }}/.config/background.png"

i3lock_options: "i3lock --image=/home/{{ user }}/.config/lockscreen.png"
# optional .bashrc commands
bash:
  bashrc: "if [ ! -f /tmp/autostart ]; then\n  /opt/start.sh \n#  ssh-add ~/.ssh/id_ed25519\nelse\n ddate;fi\n"


